# Generated by Django 5.2.13 on 2026-04-21 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='org_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
